2024-04-11 15:37:23,764 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on https://localhost:5555 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:23,764 INFO: [33mPress CTRL+C to quit[0m [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:29,818 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:29] "[32mGET / HTTP/1.1[0m" 302 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:29,836 DEBUG: Starting new HTTPS connection (1): login.microsoftonline.com:443 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1055]
2024-04-11 15:37:30,193 DEBUG: https://login.microsoftonline.com:443 "GET /common/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1547 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:549]
2024-04-11 15:37:30,199 DEBUG: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/common/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/common/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'} [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/msal/authority.py:92]
2024-04-11 15:37:30,228 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:30] "GET /login?next=/ HTTP/1.1" 200 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:30,279 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:30] "GET /static/content/bootstrap.min.css HTTP/1.1" 200 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:30,283 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:30] "GET /static/content/site.css HTTP/1.1" 200 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:30,291 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:30] "GET /static/images/sign-in-with-ms.svg HTTP/1.1" 200 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:30,292 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:30] "GET /static/scripts/modernizr-2.6.2.js HTTP/1.1" 200 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:30,293 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:30] "GET /static/scripts/jquery-1.10.2.js HTTP/1.1" 200 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:30,332 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:30] "GET /static/scripts/bootstrap.js HTTP/1.1" 200 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:30,399 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:30] "GET /static/scripts/respond.js HTTP/1.1" 200 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:40,052 DEBUG: Starting new HTTPS connection (1): login.microsoftonline.com:443 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1055]
2024-04-11 15:37:40,405 DEBUG: https://login.microsoftonline.com:443 "GET /common/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1547 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:549]
2024-04-11 15:37:40,409 DEBUG: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/common/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/common/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'} [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/msal/authority.py:92]
2024-04-11 15:37:40,961 DEBUG: https://login.microsoftonline.com:443 "POST /common/oauth2/v2.0/token HTTP/1.1" 200 3436 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:549]
2024-04-11 15:37:40,962 DEBUG: event={
    "client_id": "eef84f2a-99f2-49ea-b886-ff525085c9b4",
    "data": {
        "client_id": "eef84f2a-99f2-49ea-b886-ff525085c9b4",
        "code": "M.C501_BAY.2.U.58669070-850a-5a88-5898-ced8ad75d600",
        "redirect_uri": "https://localhost:5555/callback",
        "scope": [
            "profile",
            "offline_access",
            "openid",
            "User.Read"
        ]
    },
    "grant_type": "authorization_code",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ2ZXIiOiIxLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFESlR0R2JSeHhMOWJVZXdWUHg1YlVJIiwibmFtZSI6InRyYW4gbmd1eWVuIGJhY2giLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYmMxemJxQGdtYWlsLmNvbSIsIm9pZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC04M2JhLWQyNTAwNWY1MTVhMCIsInRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImhvbWVfb2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTgzYmEtZDI1MDA1ZjUxNWEwIiwidWlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTgzYmEtZDI1MDA1ZjUxNWEwIiwidXRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCJ9",
        "expires_in": 3600,
        "ext_expires_in": 3600,
        "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkZsR05mUnZHSW82MVJIckFUQmNucUZTb2RpOCJ9.eyJ2ZXIiOiIyLjAiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkL3YyLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFESlR0R2JSeHhMOWJVZXdWUHg1YlVJIiwiYXVkIjoiZWVmODRmMmEtOTlmMi00OWVhLWI4ODYtZmY1MjUwODVjOWI0IiwiZXhwIjoxNzEyOTExMDYwLCJpYXQiOjE3MTI4MjQzNjAsIm5iZiI6MTcxMjgyNDM2MCwibmFtZSI6InRyYW4gbmd1eWVuIGJhY2giLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYmMxemJxQGdtYWlsLmNvbSIsIm9pZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC04M2JhLWQyNTAwNWY1MTVhMCIsInRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImFpbyI6IkRqVVpaNVB2OEVTemFEOWhVNERJd0JlNUV0dFc2SUNna0JwIUlFV0dNOXF2KkF4ITZkeUdUZFZQZmlEbUo0OWZ1dWtnKlA2IUR1MlNyTTl1KlFrN1FpMUxSU3dLbjhZSVFJUUoyUnJHa3FaQWRLSDFDIWFGM3pKb1Z3cEhTQVN2TzBhZE5EZGQhOENOckQ5OXM5M0ZETG81WU5hdlgzSWEyaWxlNzg3UWY0TjgifQ.kDahYRr-5Bm5KP29Yb27tu_EEeOeG5wTg2400nSa03OFhxKX1I3W8zzcQ-baX0a_01KHrSKqe7kGUgnw-DTqA-7S7DWs2BQ6o6X0n-yPbGozYm42HFE2e853jaKo_D6AXq04VVDjSm97FJbLEUnZYGsVwNKmmEq7dD34UcwGXAPoC7iLBLSoJYYU7f24Vu5mT7jZ6bNt3Bzsm4zdd7IQDv0Ojc8kcGluapcEKU8K_gtSjelV4laTOo7D-m77aIQolWL0Ep_mBEtXDzlAvabzYKyhiJ4l-85Rgx-5ucGIJMmCPLZTVCM2QdBtjdorO6WNGDulqn3x4XCbzQmR-PPQTQ",
        "refresh_token": "********",
        "scope": "User.Read openid profile",
        "token_type": "Bearer"
    },
    "scope": [
        "User.Read",
        "openid",
        "profile"
    ],
    "token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token"
} [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/msal/token_cache.py:116]
2024-04-11 15:37:45,304 DEBUG: Starting new HTTPS connection (1): login.microsoftonline.com:443 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1055]
2024-04-11 15:37:45,693 DEBUG: https://login.microsoftonline.com:443 "GET /common/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1547 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:549]
2024-04-11 15:37:45,695 DEBUG: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/common/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/common/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'} [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/msal/authority.py:92]
2024-04-11 15:37:46,285 DEBUG: https://login.microsoftonline.com:443 "POST /common/oauth2/v2.0/token HTTP/1.1" 200 3436 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:549]
2024-04-11 15:37:46,289 DEBUG: event={
    "client_id": "eef84f2a-99f2-49ea-b886-ff525085c9b4",
    "data": {
        "client_id": "eef84f2a-99f2-49ea-b886-ff525085c9b4",
        "code": "M.C501_BAY.2.U.21cb7903-7a26-9130-2848-eaff0839229e",
        "redirect_uri": "https://localhost:5555/callback",
        "scope": [
            "profile",
            "offline_access",
            "openid",
            "User.Read"
        ]
    },
    "grant_type": "authorization_code",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ2ZXIiOiIxLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFESlR0R2JSeHhMOWJVZXdWUHg1YlVJIiwibmFtZSI6InRyYW4gbmd1eWVuIGJhY2giLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYmMxemJxQGdtYWlsLmNvbSIsIm9pZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC04M2JhLWQyNTAwNWY1MTVhMCIsInRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImhvbWVfb2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTgzYmEtZDI1MDA1ZjUxNWEwIiwidWlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTgzYmEtZDI1MDA1ZjUxNWEwIiwidXRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCJ9",
        "expires_in": 3600,
        "ext_expires_in": 3600,
        "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkZsR05mUnZHSW82MVJIckFUQmNucUZTb2RpOCJ9.eyJ2ZXIiOiIyLjAiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkL3YyLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFESlR0R2JSeHhMOWJVZXdWUHg1YlVJIiwiYXVkIjoiZWVmODRmMmEtOTlmMi00OWVhLWI4ODYtZmY1MjUwODVjOWI0IiwiZXhwIjoxNzEyOTExMDY1LCJpYXQiOjE3MTI4MjQzNjUsIm5iZiI6MTcxMjgyNDM2NSwibmFtZSI6InRyYW4gbmd1eWVuIGJhY2giLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYmMxemJxQGdtYWlsLmNvbSIsIm9pZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC04M2JhLWQyNTAwNWY1MTVhMCIsInRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImFpbyI6IkRtMUowdHMyZjN2d0lNZmVnWERRYUFPenR4SHlpIXJOdTRyZ2JxclhDYkVOTmVIZWNZbEF2VFFTallJVTQxQThRTiFkTkFZeDV6Zkh6MVVpd1ByeFZrRFJsVk5pWnh1IUNWKnN2bWtIclMycjF4RXh6OUlkcEtYQSFVMkRRU2NrajJxWTdGaXdIMUpGdTM1SVRBNHd1a3Q0Y285bVJOaWVhWjgza3E3TzlrRHIifQ.D3vdDSUGr10AAi7ZI4CPu5yoVBZ8HhpoxqwK1pVnap2phLuQLmwTC7sMaDXZBm3OdwO4-3q7snChbj_wGS7BOusz5codB7TnJ2nCyBFMvzt2fUZCR8oxoqlQ_NnjFnWDfHwLueVBqlvnqfWa3HJsHlG6cKY2lOLng4-n9WANXkIzU9SFH0roaEuCdwot33XrOtf6zoH2eDvoiQnHgHwQdKIQRxO_LnVDIXA3wWgylUQFCEOFo5CqGQYzPC1KcNKKQ79KvXMm3agJvgUZ4plSnY98Z8CSxrFArKe1s6v0xzsO8iS4mGdVS4WS4Toe6tqlXmc9fFpW_rxxIcNJ87bcHw",
        "refresh_token": "********",
        "scope": "User.Read openid profile",
        "token_type": "Bearer"
    },
    "scope": [
        "User.Read",
        "openid",
        "profile"
    ],
    "token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token"
} [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/msal/token_cache.py:116]
2024-04-11 15:37:51,358 DEBUG: Starting new HTTPS connection (1): login.microsoftonline.com:443 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:1055]
2024-04-11 15:37:51,752 DEBUG: https://login.microsoftonline.com:443 "GET /common/v2.0/.well-known/openid-configuration HTTP/1.1" 200 1547 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:549]
2024-04-11 15:37:51,758 DEBUG: openid_config = {'token_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/token', 'token_endpoint_auth_methods_supported': ['client_secret_post', 'private_key_jwt', 'client_secret_basic'], 'jwks_uri': 'https://login.microsoftonline.com/common/discovery/v2.0/keys', 'response_modes_supported': ['query', 'fragment', 'form_post'], 'subject_types_supported': ['pairwise'], 'id_token_signing_alg_values_supported': ['RS256'], 'response_types_supported': ['code', 'id_token', 'code id_token', 'id_token token'], 'scopes_supported': ['openid', 'profile', 'email', 'offline_access'], 'issuer': 'https://login.microsoftonline.com/{tenantid}/v2.0', 'request_uri_parameter_supported': False, 'userinfo_endpoint': 'https://graph.microsoft.com/oidc/userinfo', 'authorization_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize', 'device_authorization_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/devicecode', 'http_logout_supported': True, 'frontchannel_logout_supported': True, 'end_session_endpoint': 'https://login.microsoftonline.com/common/oauth2/v2.0/logout', 'claims_supported': ['sub', 'iss', 'cloud_instance_name', 'cloud_instance_host_name', 'cloud_graph_host_name', 'msgraph_host', 'aud', 'exp', 'iat', 'auth_time', 'acr', 'nonce', 'preferred_username', 'name', 'tid', 'ver', 'at_hash', 'c_hash', 'email'], 'kerberos_endpoint': 'https://login.microsoftonline.com/common/kerberos', 'tenant_region_scope': None, 'cloud_instance_name': 'microsoftonline.com', 'cloud_graph_host_name': 'graph.windows.net', 'msgraph_host': 'graph.microsoft.com', 'rbac_url': 'https://pas.windows.net'} [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/msal/authority.py:92]
2024-04-11 15:37:52,739 DEBUG: https://login.microsoftonline.com:443 "POST /common/oauth2/v2.0/token HTTP/1.1" 200 3436 [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/urllib3/connectionpool.py:549]
2024-04-11 15:37:52,746 DEBUG: event={
    "client_id": "eef84f2a-99f2-49ea-b886-ff525085c9b4",
    "data": {
        "client_id": "eef84f2a-99f2-49ea-b886-ff525085c9b4",
        "code": "M.C501_BAY.2.U.5b677962-77ce-0ce4-cd20-ac1c1681bd95",
        "redirect_uri": "https://localhost:5555/callback",
        "scope": [
            "profile",
            "offline_access",
            "openid",
            "User.Read"
        ]
    },
    "grant_type": "authorization_code",
    "params": null,
    "response": {
        "access_token": "********",
        "client_info": "eyJ2ZXIiOiIxLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFESlR0R2JSeHhMOWJVZXdWUHg1YlVJIiwibmFtZSI6InRyYW4gbmd1eWVuIGJhY2giLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYmMxemJxQGdtYWlsLmNvbSIsIm9pZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC04M2JhLWQyNTAwNWY1MTVhMCIsInRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImhvbWVfb2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTgzYmEtZDI1MDA1ZjUxNWEwIiwidWlkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLTgzYmEtZDI1MDA1ZjUxNWEwIiwidXRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCJ9",
        "expires_in": 3600,
        "ext_expires_in": 3600,
        "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkZsR05mUnZHSW82MVJIckFUQmNucUZTb2RpOCJ9.eyJ2ZXIiOiIyLjAiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkL3YyLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFESlR0R2JSeHhMOWJVZXdWUHg1YlVJIiwiYXVkIjoiZWVmODRmMmEtOTlmMi00OWVhLWI4ODYtZmY1MjUwODVjOWI0IiwiZXhwIjoxNzEyOTExMDcyLCJpYXQiOjE3MTI4MjQzNzIsIm5iZiI6MTcxMjgyNDM3MiwibmFtZSI6InRyYW4gbmd1eWVuIGJhY2giLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhYmMxemJxQGdtYWlsLmNvbSIsIm9pZCI6IjAwMDAwMDAwLTAwMDAtMDAwMC04M2JhLWQyNTAwNWY1MTVhMCIsInRpZCI6IjkxODgwNDBkLTZjNjctNGM1Yi1iMTEyLTM2YTMwNGI2NmRhZCIsImFpbyI6IkR2dCpDUkJuQmdpem14VyFhTjIqYlNMVlV6N2ZEMmllVmtFMUlYS2hjaElUaWp1UWtUNFM5cDBLQ01DIXJmemI1d2lDejR5QmEyMERybmpmR0NjQiFPVXpsSTNYWDcxYUhZRXdHNGNpMkp5UDVvYW9zeGdTWHFjRWtzMjIqWDc2ZzJ4ZTh3Mk1wVVhlcHVDamx1NHpYejZaTk5sZHp4b1d6Q1ZzNzhJVFBwd1UifQ.OUqad2h4H3VwnAGgnhtDe1rc-XnfuOYJfW0939obFSb--Szr-f3M8d8rqFp6arx7CA3WrQ0BcPe6qPZGFlqmGMprMa94gd8Ntzw7widjrXfKuQMlfzeGfp9RgG2qr1if3HfO5YkXn55-bPwfOYeXH0vPArLpq3idPOBHfBlZa5NWrIOWhTeLei5O7aPd3LIn218YLMkl_X_a2FRA853JYO6rHh9MGrhP7R2Ee8OGoDvdEohoRBgYvv4_hdmDQTQtPpuR1DN5_BQ6wH9RjmauzDs3r0z8mwPO-4Deh24GmIzzX2ma-R9KntIgSOY6O1lwOde4CyjJ0WdI_46F6QMgTg",
        "refresh_token": "********",
        "scope": "User.Read openid profile",
        "token_type": "Bearer"
    },
    "scope": [
        "User.Read",
        "openid",
        "profile"
    ],
    "token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token"
} [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/msal/token_cache.py:116]
2024-04-11 15:37:55,980 ERROR: Exception on /callback [GET] [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/FlaskWebProject/views.py", line 103, in authorized
    user = User.query.filter_by(username="admin").first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2748, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2431, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-04-11 15:37:56,013 INFO: 127.0.0.1 - - [11/Apr/2024 15:37:56] "[35m[1mGET /callback?code=M.C501_BAY.2.U.58669070-850a-5a88-5898-ced8ad75d600&state=635b372a-4dbc-44ea-b7b5-ecf3b23fc006 HTTP/1.1[0m" 500 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:37:56,026 ERROR: Error on request:
Traceback (most recent call last):
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 326, in execute
    write(data)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 301, in write
    self.wfile.write(data)
  File "/home/bachtn/.pyenv/versions/3.12.3/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
  File "/home/bachtn/.pyenv/versions/3.12.3/lib/python3.12/ssl.py", line 1211, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/.pyenv/versions/3.12.3/lib/python3.12/ssl.py", line 1180, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406) [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:38:01,296 ERROR: Exception on /callback [GET] [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/FlaskWebProject/views.py", line 103, in authorized
    user = User.query.filter_by(username="admin").first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2748, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2431, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-04-11 15:38:01,314 INFO: 127.0.0.1 - - [11/Apr/2024 15:38:01] "[35m[1mGET /callback?code=M.C501_BAY.2.U.21cb7903-7a26-9130-2848-eaff0839229e&state=635b372a-4dbc-44ea-b7b5-ecf3b23fc006 HTTP/1.1[0m" 500 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:38:01,316 ERROR: Error on request:
Traceback (most recent call last):
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 326, in execute
    write(data)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/serving.py", line 301, in write
    self.wfile.write(data)
  File "/home/bachtn/.pyenv/versions/3.12.3/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
  File "/home/bachtn/.pyenv/versions/3.12.3/lib/python3.12/ssl.py", line 1211, in sendall
    v = self.send(byte_view[count:])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/.pyenv/versions/3.12.3/lib/python3.12/ssl.py", line 1180, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406) [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
2024-04-11 15:38:07,751 ERROR: Exception on /callback [GET] [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/FlaskWebProject/views.py", line 103, in authorized
    user = User.query.filter_by(username="admin").first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2748, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2847, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2180, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2047, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1143, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3269, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2431, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3293, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1269, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 645, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 616, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-04-11 15:38:07,771 INFO: 127.0.0.1 - - [11/Apr/2024 15:38:07] "[35m[1mGET /callback?code=M.C501_BAY.2.U.5b677962-77ce-0ce4-cd20-ac1c1681bd95&state=635b372a-4dbc-44ea-b7b5-ecf3b23fc006 HTTP/1.1[0m" 500 - [in /home/bachtn/learn/azure/nd081/cd1756-Azure-Applications-project/.venv/lib/python3.12/site-packages/werkzeug/_internal.py:96]
